layout_spectrum: 1
typography_spectrum: 0.1105137
color:
  saturation: 1
  lightness: 1
  brandStrength: 0.6810186
  rhythmicContrast: 1
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: 'Alex Armando Torres Photography '
